Upgrade prototype kit to v13
DFE-Digital/publish-teacher-training-prototype pull request #397
Opened 2024-05-02 17:28 UTC by simonwhatley

2024-05-02 21:33 UTC, avinhurry requested changes
![image](https://github.com/DFE-Digital/publish-teacher-training-prototype/assets/50492247/647b050b-6d93-4960-93e3-b1e9b0a17471)

![image](https://github.com/DFE-Digital/publish-teacher-training-prototype/assets/50492247/e08947c3-d86e-40a1-99f4-7f1693004b48)

2024-05-02 21:40 UTC, avinhurry requested changes
<img width="884" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training-prototype/assets/50492247/58c7218f-7012-449a-bf43-de4ee2d801ba">

2024-05-03 15:29 UTC, simonwhatley commented
@avinhurry, can you please confirm the changes you suggest I make? 🙌 I'm trying not to change the prototype page designs; I'm just migrating them to v13 of the prototype kit.

Having said that, I've updated the tags to match production. This also matches the v12 prototype.

From the second screenshot, do you think the summary list shouldn't be full-width? It's full-width because of the long-form content, but it looks odd when there isn't any content.

Finally, the footer links. They're small compared to the newer designs. If needed, someone on the Find and Apply team could update them.

2024-05-07 16:53 UTC, avinhurry approved these changes

2024-05-08 07:48 UTC, merged